### ISSUE TITLE
Document Operate client access (API) via OAuth2 

### ISSUE THREAD

**Issue by ralfpuchert** [camunda-cloud/camunda-cloud-documentation#616]
## Description
Operate provides a public API that is accessible by an authenticated user or client.
* On-prem: API can be accessed by using Basic Authentication
* CCSaaS: API can be accessed by using [OAuth2 client credentials flow](https://auth0.com/docs/get-started/authentication-and-authorization-flow/client-credentials-flow)

## TODO

- [x] Describe how to obtain an access token
- [x] Describe how to enable `OAuth2 client credentials flow` access in Operate
- [x] Describe an end-to-end example
